package com.daniel.cxf.demo.first.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-28T15:39:48.037+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://cxf.service.first.demo.cxf.daniel.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf.service.first.demo.cxf.daniel.com/", className = "com.daniel.cxf.demo.first.service.client.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf.service.first.demo.cxf.daniel.com/", className = "com.daniel.cxf.demo.first.service.client.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCatsByUser", targetNamespace = "http://cxf.service.first.demo.cxf.daniel.com/", className = "com.daniel.cxf.demo.first.service.client.GetCatsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatsByUserResponse", targetNamespace = "http://cxf.service.first.demo.cxf.daniel.com/", className = "com.daniel.cxf.demo.first.service.client.GetCatsByUserResponse")
    public java.util.List<com.daniel.cxf.demo.first.service.client.Cat> getCatsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.daniel.cxf.demo.first.service.client.User arg0
    );
}
