package com.daniel.cxf.demo.first.service.cxf.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.daniel.cxf.demo.first.service.cxf.HelloService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-28T14:58:00.620+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "Hellossss", 
                  wsdlLocation = "http://localhost:8080/Hellossss?wsdl",
                  targetNamespace = "http://impl.cxf.service.first.demo.cxf.daniel.com/") 
public class Hellossss extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.cxf.service.first.demo.cxf.daniel.com/", "Hellossss");
    public final static QName HelloServiceImplPort = new QName("http://impl.cxf.service.first.demo.cxf.daniel.com/", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Hellossss?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Hellossss.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Hellossss?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Hellossss(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Hellossss(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hellossss() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Hellossss(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Hellossss(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Hellossss(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, HelloService.class, features);
    }

}
